vacuum_clean_zone:
  description: Start the cleaning operation in the selected area.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    zone:
      description: Coordinates.
      example: "819,-263,4424,2105"
    repeats:
      description: Number of cleaning repeats for each zone between 1 and 3. Does nothing at the moment!.
      example: "1"

vacuum_set_restricted_zone:
  description: Define a restricted zone.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    zone:
      description: Array of coordinates.
      example: '"{"vw":{"line":[],"rect":[[819,-263,4424,2105],[-2001,-3050,-542,515]],"mop":[]}}"'

vacuum_remote_control_move_step:
  description: Remotely control move the bot one step.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    rotation:
      description: Turn in binary degrees between -128 and 128.
      example: "64"
    velocity:
      description: Move speed, from 100 (forward) to -300 (backward)
      example: "100"

vacuum_set_water_level:
  description: Set water level for mopping.
  target:
    entity:
      domain: vacuum
  fields:
    water_level:
      description: water level, 1:low, 2:medium, 3:high
      default: "Medium"
      required: true
      selector:
        select:
          options:
            - "Low"
            - "Medium"
            - "High"

vacuum_install_voice_pack:
  description: Install official or custom voice pack.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    lang_id:
      description: "Language ID of this pack"
      example: "DE"
      required: true
    url:
      description: "Url of this pack it should be reachable by the vacuum bot"
      example: "http://awsde0.fds.api.xiaomi.com/dreame-product/dreame.vacuum.p2009/voices/package/deyu.tar.gz"
      required: true
    md5:
      description: "MD5 checksum of the language pack"
      example: "d25986c1f608c0897475707e77d856f9"
      required: true
    size:
      description: "Size of the language pack in bytes"
      example: 4067845
      required: true

vacuum_set_clean_cloth_tip:
  description: Set delay of clean cloth reminder.
  target:
    entity:
      domain: vacuum
  fields:
    entity_id:
      description: Name of the vacuum entity.
      example: "vacuum.dreame_d9"
    delay:
      description: "Delay in minutes. (0 = disable)"
      example: 45
      required: true
      selector:
        number:
          min: 0
          max: 120
